export const Arrays = {
    cities: {
        "en": [
            "Baghdad",
            "Babil",
            "Basra",
            "Dhi Qar",
            "Al-Qadisiyyah",
            "Diyala",
            "Duhok",
            "Erbil",
            "Karbala",
            "Kirkuk",
            "Maysan",
            "Muthanna",
            "Najaf",
            "Ninawa",
            "Salah Al-Din",
            "Sulaymaniyah",
            "Wasit"
        ], "ar": ["بغداد",
            "بابل",
            "البصرة",
            "ذي قار",
            "القادسية",
            "ديالى",
            "دهوك",
            "أربيل",
            "كربلاء",
            "كركوك",
            "ميسان",
            "المثنى",
            "النجف",
            "نينوى",
            "صلاح الدين",
            "السليمانية",
            "واسط"]
    },
    departments: [
        "Public Health - الصحه العامة",
        "Architecture - العمارة",
        "English Language - اللغة الإنجليزية",
        "Laws - القانون",
        "Engineering - الهندسة",
        "Interior Design - التصميم الداخلي",
        "Arts - الفنون",
        "Nursing - التمريض",
        "Dentistry - طب الأسنان",
        "Education - التربية",
        "Computer Science - علوم الحاسب",
        "Mathematics - الرياضيات",
        "Medicine - الطب",
        "Physical Education - التربية البدنية",
        "Physics - الفيزياء",
        "Geology - الجيولوجيا",
        "Pharmacy - الصيدلة",
        "Agriculture - الزراعة",
        "Psychology - علم النفس",
        "Sociology - علم الاجتماع",
        "Economics - الاقتصاد",
        "Political Science - العلوم السياسية",
        "Islamic Studies - الدراسات الإسلامية",
        "Media - الإعلام",
        "History - التاريخ",
        "Chemistry - الكيمياء",
        "Geography - الجغرافيا",
        "Statistics - الإحصاء",
        "Biology - الأحياء",
        "Tourism - السياحة",
        "Hotel Management - إدارة الفنادق",
        "Business Administration - إدارة الأعمال",
        "Accounting - المحاسبة",
        "Environmental Science - العلوم البيئية",
        "Veterinary Medicine - الطب البيطري",
        "Social Work - العمل الاجتماعي",
        "Linguistics - علم اللغة",
        "Anthropology - علم الإنسان",
        "Archaeology - علم الآثار",
        "Library Science - علوم المكتبات",
        "Education Technology - تكنولوجيا التعليم",
        "Special Education - التربية الخاصة",
        "Music - الموسيقى",
        "Fine Arts - الفنون الجميلة",
        "Drama - الدراما",
        "Communication - الاتصالات",
        "Fashion Design - تصميم الأزياء",
        "Graphic Design - التصميم الجرافيكي",
        "Marketing - التسويق",
        "Human Resources - الموارد البشرية",
        "Supply Chain Management - إدارة سلسلة التوريد",
        "International Relations - العلاقات الدولية",
        "Journalism - الصحافة",
        "Advertising - الإعلان",
        "Public Relations - العلاقات العامة",
        "Radio and Television - الإذاعة والتلفزيون",
        "Film Studies - دراسات الأفلام",
        "Publishing - النشر",
        "Translation - الترجمة"
    ],
    places: [
        "Deliver To Home",
        "07731022221 | شركة الرغد للبطاقات | بغداد - باب المعظم",
        "07742929251 | شركة هناء العراق للتوصيل | الكرخ - السيدية",
        "07735977810 | شركة ركن التجارة للتوصيل | الكرخ - حي الجامعة",
        "07755681515 | شركة شراع العين للتوصيل | الكرخ - حي الجامعة",
        "07704337139 | شركة مرسال للتوصيل | الكرخ - حي العامل",
        "07707775995 | شركة الانتشار السريع للتوصيل | الكرخ - حي الاعلام",
        "07734667259 | شركة المعهد العراقي للتوصيل | الكرخ - حي البياع",
        "07801004580 | شركة المرجان للتوصيل | الكرخ - حي البياع",
        "07801084488 | شركة النوارس السريعة للتوصيل | الكرخ - حي الغزالية",
        "07802552008 | شركة التقوى للتوصيل | الكرخ - حي الدورة",
        "07830636661 | شركة المها للتوصيل | الكرخ - حي المواصلات",
        "07506906555 | شركة الميس للتوصيل | الكرخ - حي العامل",
        "07503697777 | شركة كركوك النصرانية | اربيل",
        "07501008214 | شركة شمس العراق للتوصيل | بابل - الحلة",
        "07711000982 | شركة عبر المدن للتوصيل العامة | مجمع مستشفى - بابل",
        "07700286469 | شركة الإبراز للتوصيل | بابل - كربلاء",
        "07715519554 | شركة المدار السريع للتوصيل | بابل - الحلة",
        "07801206751 | شركة الرغد للتوصيل | بابل - الحلة",
        "07712302320 | شركة الكرخ العصرية للتوصيل | بغداد - السيدية",
        "07854106701 | شركة المعبر العصرية للتوصيل | بابل - الحلة",
        "07830555339 | شركة المسافر للتوصيل | بابل - الحلة",
        "07723000775 | شركة البريد السريع للتوصيل | بغداد - الحارثية",
        "07725013779 | شركة الاسد السريع للتوصيل | بغداد - البياع",
        "07806576709 | شركة النجاح للتوصيل | بغداد - حي الجهاد",
        "07804873166 | شركة العز للتوصيل | بغداد - الغزالية",
        "07709937510 | شركة الرافدين السريعة للتوصيل | بغداد - السيدية",
        "07828883111 | شركة عراق للتوصيل | بغداد - الحارثية"
    ],
    nationalitis: [
        "Afghan - أفغاني",
        "Congolese - كونغولي",
        "Costa Rican - كوستاريكي",
        "Croatian - كرواتي",
        "Cuban - كوبي",
        "Cypriot - قبرصي",
        "Czech - تشيكي",
        "Danish - دنماركي",
        "Djiboutian - جيبوتي",
        "Dominican - دومينيكاني",
        "Dutch - هولندي",
        "East Timorese - تيموري شرقي",
        "Ecuadoran - إكوادوري",
        "Egyptian - مصري",
        "Emirati - إماراتي",
        "Equatorial Guinean - غيني استوائي",
        "Eritrean - إريتيري",
        "Estonian - إستوني",
        "Ethiopian - إثيوبي",
        "Fijian - فيجي",
        "Filipino - فلبيني",
        "Finnish - فنلندي",
        "French - فرنسي",
        "Gabonese - غابوني",
        "Gambian - غامبي",
        "Georgian - جورجي",
        "German - ألماني",
        "Ghanaian - غاني",
        "Greek - يوناني",
        "Grenadan - غرينادي",
        "Guatemalan - غواتيمالي",
        "Guinean - غيني",
        "Guyanese - غوياني",
        "Haitian - هايتي",
        "Honduran - هندوراسي",
        "Hungarian - مجري",
        "Icelander - آيسلندي",
        "Indian - هندي",
        "Indonesian - إندونيسي",
        "Iranian - إيراني",
        "Irish - إيرلندي",
        "Albanian - ألباني",
        "Algerian - جزائري",
        "American - أمريكي",
        "Andorran - أندوري",
        "Angolan - أنغولي",
        "Argentine - أرجنتيني",
        "Armenian - أرميني",
        "Australian - أسترالي",
        "Austrian - نمساوي",
        "Azerbaijani - أذربيجاني",
        "Bahamian - بهامي",
        "Bangladeshi - بنغلادشي",
        "Barbadian - باربادوسي",
        "Belarusian - بيلاروسي",
        "Belgian - بلجيكي",
        "Belizean - بليزي",
        "Beninese - بنيني",
        "Bolivian - بوليفي",
        "Bosnian - بوسني",
        "Botswanan - بوتسواني",
        "Brazilian - برازيلي",
        "British - بريطاني",
        "Bruneian - برونايي",
        "Bulgarian - بلغاري",
        "Burkinabe - بوركيني",
        "Burmese - بورمي",
        "Burundian - بوروندي",
        "Cambodian - كمبودي",
        "Cameroonian - كاميروني",
        "Canadian - كندي",
        "Cape Verdean - رأس أخضري",
        "Central African - أفريقي أوسطي",
        "Chadian - تشادي",
        "Chilean - تشيلي",
        "Chinese - صيني",
        "Colombian - كولومبي",
        "Comorian - جزر القمر", "Tajik - طاجيكي",
        "Tanzanian - تنزاني",
        "Thai - تايلاندي",
        "Togolese - توغولي",
        "Tongan - تونغي",
        "Trinidadian - ترينيدادي",
        "Tunisian - تونسي",
        "Turkish - تركي",
        "Turkmen - تركماني",
        "Tuvaluan - توفالي",
        "Ugandan - أوغندي",
        "Ukrainian - أوكراني",
        "Uruguayan - أوروغوياني",
        "Uzbek - أوزبكي",
        "Vanuatuan - فانواتي",
        "Venezuelan - فنزويلي",
        "Vietnamese - فيتنامي",
        "Yemeni - يمني",
        "Zambian - زامبي",
        "Zimbabwean - زيمبابوي",
        "South Korean - كوري جنوبي",
        "South Sudanese - جنوب سوداني",
        "Spanish - إسباني",
        "Sri Lankan - سريلانكي",
        "Sudanese - سوداني",
        "Surinamese - سورينامي",
        "Swazi - سوازيلندي",
        "Swedish - سويدي",
        "Swiss - سويسري",
        "Syrian - سوري",
        "Taiwanese - تايواني",
        "Russian - روسي",
        "Rwandan - رواندي",
        "Saint Kitts and Nevis - سانت كيتس ونيفيس",
        "Saint Lucian - سانت لوسي",
        "Saint Vincentian - سانت فنسنتي",
        "Salvadoran - سلفادوري",
        "Samoan - ساموا",
        "San Marinese - سان مارينو",
        "Sao Tomean - ساو تومي وبرينسيب",
        "Saudi Arabian - سعودي",
        "Senegalese - سنغالي",
        "Serbian - صربي",
        "Seychellois - سيشلي",
        "Sierra Leonean - سيراليوني",
        "Singaporean - سنغافوري",
        "Slovak - سلوفاكي",
        "Slovenian - سلوفيني",
        "Solomon Islander - من جزر سليمان",
        "Somali - صومالي",
        "South African - جنوب أفريقي",
        "Italian - إيطالي",
        "Ivorian - إيفواري",
        "Jamaican - جامايكي",
        "Japanese - ياباني",
        "Jordanian - أردني",
        "Kazakh - كازاخستاني",
        "Kenyan - كيني",
        "Kiribati - كيريباتي",
        "Korean - كوري",
        "Kosovan - كوسوفي",
        "Kuwaiti - كويتي",
        "Kyrgyz - قيرغيزستاني",
        "Latvian - لاتفي",
        "Lebanese - لبناني",
        "Lesotho - ليسوتو",
        "Liberian - ليبيري",
        "Libyan - ليبي",
        "Liechtenstein - ليختنشتايني",
        "Lithuanian - ليتواني",
        "Luxembourger - لوكسمبورغي",
        "Macedonian - مقدوني",
        "Malagasy - مدغشقري",
        "Malawian - مالاوي",
        "Malaysian - ماليزي",
        "Maldivian - مالديفي",
        "Malian - مالي",
        "Maltese - مالطي",
        "Marshallese - مارشالي",
        "Mauritanian - موريتاني",
        "Mauritian - موريشيوسي",
        "Mexican - مكسيكي",
        "Micronesian - ميكرونيزي",
        "Moldovan - مولدافي",
        "Monegasque - موناكي",
        "Mongolian - منغولي",
        "Montenegrin - مونتينيغري",
        "Moroccan - مغربي",
        "Namibian - ناميبي",
        "Nauruan - ناوروي",
        "Nepalese - نيپالي",
        "New Zealander - نيوزيلندي",
        "Nicaraguan - نيكاراغوي",
        "Nigerian - نيجيري",
        "North Korean - كوري شمالي",
        "Norwegian - نرويجي",
        "Omani - عماني",
        "Pakistani - باكستاني",
        "Palauan - بالاو",
        "Palestinian - فلسطيني",
        "Panamanian - بنمي",
        "Papua New Guinean - غيني",
        "Paraguayan - باراغواي",
        "Peruvian - بيروفي",
        "Polish - بولندي",
        "Portuguese - برتغالي",
        "Qatari - قطري",
        "Romanian - روماني"
    ]
}